function CueDSet = computeCueDerivs(CueDSet)
% Takes the structure which stores information at the level of the cues,
% CueDSet, and computes various additional quantitiles, and adds these as
% extra fields. Function requires CueDSet to already have various fields
% that relate to the response given. A CueDSet with these fields can be 
% generated by using the function convertDSet.m

% HISTORY
% 2021, JCT
% 16.05.2023 Updated for Coimbra data


%% Compute demeaned CueLoc
% For trials from the inferred condition, we want to know the cue location,
% but with the mean cue location under the active rule subtracted off.

tol = 0.1;
DForm = findDataFormat(CueDSet);

for iP = 1 : length(CueDSet.P)
    ThisData = CueDSet.P(iP).Data;
    cueLocDemeaned = nan(size(ThisData.TrialNum));
    
    blockTypes = DForm.BlockTypes;
    blkTypeAssocCatForCue = DForm.BlkTypeAssocCatForCue;
    for iBT = 1 : length(blockTypes)
        
        thisBlkType = blockTypes{iBT};
        thisCatForCue = blkTypeAssocCatForCue{iBT};
        theseBlkTrials = strcmp(ThisData.BlockType, thisBlkType);
        if sum(theseBlkTrials) == 0
            continue
        end
        
        assert(all(isnan(cueLocDemeaned(theseBlkTrials))))
        thisCatForCueData = ThisData.(thisCatForCue);
        assert(isequal(unique(thisCatForCueData(theseBlkTrials)), [0; 1]))
    
        for iRule = [0, 1]
            relTrials = theseBlkTrials ...
                & (ThisData.(thisCatForCue) == iRule);

            meanDataLoc = mean(ThisData.CueLoc(relTrials));

            assert(CueDSet.Spec.CueMeanDiff > 0)
            if iRule == 1
                meanExpectLoc = CueDSet.Spec.CueMeanDiff / 2;
            elseif iRule == 0
                meanExpectLoc = - CueDSet.Spec.CueMeanDiff / 2;
            else
                error('Bug')
            end

            diff = abs(meanDataLoc - meanExpectLoc);
            tol = min([tol, ...
                abs(meanDataLoc * 0.15), abs(meanExpectLoc * 0.15)]);
            assert(diff < tol)

            cueLocDemeaned(relTrials) = ThisData.CueLoc(relTrials) ...
                - meanExpectLoc;

            runDemeanedCheck(cueLocDemeaned(relTrials), tol)
        end
    end
    
    runDemeanedCheck(cueLocDemeaned, tol)
    assert(~any(isnan(cueLocDemeaned)))
    
    CueDSet.P(iP).Data.CueLocDemeaned = cueLocDemeaned;
end


end


function runDemeanedCheck(dataPoints, tol)

% INPUT
% tol: scalar or nan. Sets the tolerance. If nan a default tolerance is
% applied.

if isnan(tol)
    tol = (2 * (nanstd(dataPoints) / sqrt(sum(~isnan(dataPoints)))));
end

meanVal = mean(dataPoints, "omitnan");
assert(~isnan(meanVal))
if abs(meanVal) > tol
    error('Demeaning may not be working.')
end

end






