function [TrialData, CueData] = computeRelativeTimes(TrialData, CueData)
% Converts times from absolute, to times relative to the fixation flip on
% each trial. For some fields it allows a tolerance, to account for
% "headstart" that we sometimes give psychtoolbox. 

% HISTORY
% 2020-2021, JCT
% 07.02.2023 Read through, including called functions

HEADSTART_TOL = 0.005;

% Set all times to be given relative to the time the fixation cross flipped
trialDataFieldsToLeave = ...
    {'TrialNum', ...
    'BlockNum', ...
    'BlockType', ...             
    'SessionNum', ...            
    'NumCuesInTrial', ...        
    'CueDuration', ...           
    'StimIsHoriz', ...           
    'RuleIsHorizToLeftForTrial', ...     
    'RespIsLeft', ...            
    'Acc', ...   
    'RtIsValid', ...
    'HazardRate', ...            
    'ApproxTrialDuration', ...   
    'WasPreStimPress', ...
    'StimPhase_1', ...           
    'StimPhase_2'};   
trialDataFieldsToChange = {...
    'RtAbs', ...
    'FixFlipTime', ...
    'FixFlipEnd', ...
    'FixFlipEnd2', ...
    'StimClearRequestedTime', ...
    'StimClearTime', ...
    'StimClearEndTime', ...
    'FixRotateTimeRequested', ...
    'FixRotateTime', ...
    'FixRotateEndTime', ...
    'StimRequestedTime_1', ...
    'StimFlipTime_1', ...
    'StimFlipEnd_1', ...
    'StimRequestedTime_2', ...
    'StimFlipTime_2', ...
    'StimFlipEnd_2'};
cueDataFieldsToLeave = ...
    {'CueID', ...                
    'TrialNum', ...             
    'RuleIsHorizToLeftForCue', ...    
    'CueLoc', ...               
    'CueDuration', ...          
    'TimeBetweenCues'};
cueDataFieldsToChange = {...
    'CueRequestedTime', ...
    'CueFlipTime', ...
    'CueFlipEnd', ...
    'CueRequestedClearTime', ...
    'CueClearTime', ...
    'CueClearEnd'};

% Find the reference time for each trial 
refTime = TrialData.FixFlipTime;

% Subtract off the reference for TrialData
allFields = fieldnames(TrialData);
for iF = 1 : length(allFields)
    if ismember(allFields{iF}, trialDataFieldsToLeave)
        continue
        
    elseif ismember(allFields{iF}, trialDataFieldsToChange)
        
        TrialData.(allFields{iF}) = TrialData.(allFields{iF}) - refTime;
        assert(all(TrialData.(allFields{iF}) >= 0))
    else
        error('Unexpected field')
    end
end

% Subtract off the reference for CueData, first finding the correct
% reference for each cue
assert(isequal(TrialData.TrialNum, [1:length(TrialData.TrialNum)]'))
cueRefTime = refTime(CueData.TrialNum);

allFields = fieldnames(CueData);
for iF = 1 : length(allFields)
    if ismember(allFields{iF}, cueDataFieldsToLeave)
        continue
        
    elseif ismember(allFields{iF}, cueDataFieldsToChange)
        
        CueData.(allFields{iF}) = CueData.(allFields{iF}) - cueRefTime;
        
        if strcmp(allFields{iF}, 'CueRequestedTime')
            assert(all(CueData.(allFields{iF}) >= -HEADSTART_TOL))
        else
            assert(all(CueData.(allFields{iF}) >= 0))
        end
    else
        error('Unexpected field')
    end
end

% Rename the RT field after computing relative times
assert(~ismember('RT', fieldnames(TrialData)))
TrialData.RT = TrialData.RtAbs;
TrialData = rmfield(TrialData, 'RtAbs');

