function incParams = findIncParams(modelName)
% Find a cell vector of the names of the parameters included in the model
% with name modelName

allModelNames = { ...
    'normative-no-noise', ...
    'miscal-h-b-normative', ...
    'miscal-h-normative', ...
    'normative', ...
    'last-sample', ...
    'perfect-acc', ...
    'bound-acc', ...
    'leaky-acc', ...
    };
allIncludedParams = { ...
    {}', ...
    {'ObserverH', 'ObserverBeta', 'DecisionNoiseSigma'}', ...
    {'ObserverH', 'DecisionNoiseSigma'}', ...
    {'DecisionNoiseSigma'}', ...
    {'DecisionNoiseSigma'}', ...
    {'DecisionNoiseSigma'}', ...
    {'DecisionNoiseSigma', 'AccumBound'}', ...
    {'DecisionNoiseSigma', 'AccumLeak'}'
    };

% Add variants of every model with a lapse rate
wantLapseVersion = allModelNames(2:end);
wantLapseVersionParams = allIncludedParams(2:end);
lapseModelNames = cell(1, length(wantLapseVersion));
lapseIncludedParams = cell(1, length(wantLapseVersion));

for iM = 1 : length(wantLapseVersion)
    lapseModelNames{iM} = [wantLapseVersion{iM} '-lapse'];
    lapseIncludedParams{iM} = [wantLapseVersionParams{iM}; {'LapseRate'}];
end

allModelNames = [allModelNames, lapseModelNames];
allIncludedParams = [allIncludedParams, lapseIncludedParams];

matchMask = strcmp(modelName, allModelNames);
if sum(matchMask) ~= 1
    error(['Either model name (' modelName ') unrecognised or bug'])
end
incParams = allIncludedParams{matchMask};
